// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.19.4
// source: protos/flagr.proto

package pbs

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// ReleaseFlagSrvClient is the client API for ReleaseFlagSrv service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ReleaseFlagSrvClient interface {
	CreateReleaseFlag(ctx context.Context, in *CreateReleaseFlagRequest, opts ...grpc.CallOption) (*CreateReleaseFlagResponse, error)
}

type releaseFlagSrvClient struct {
	cc grpc.ClientConnInterface
}

func NewReleaseFlagSrvClient(cc grpc.ClientConnInterface) ReleaseFlagSrvClient {
	return &releaseFlagSrvClient{cc}
}

func (c *releaseFlagSrvClient) CreateReleaseFlag(ctx context.Context, in *CreateReleaseFlagRequest, opts ...grpc.CallOption) (*CreateReleaseFlagResponse, error) {
	out := new(CreateReleaseFlagResponse)
	err := c.cc.Invoke(ctx, "/pbs.ReleaseFlagSrv/CreateReleaseFlag", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ReleaseFlagSrvServer is the server API for ReleaseFlagSrv service.
// All implementations must embed UnimplementedReleaseFlagSrvServer
// for forward compatibility
type ReleaseFlagSrvServer interface {
	CreateReleaseFlag(context.Context, *CreateReleaseFlagRequest) (*CreateReleaseFlagResponse, error)
	mustEmbedUnimplementedReleaseFlagSrvServer()
}

// UnimplementedReleaseFlagSrvServer must be embedded to have forward compatible implementations.
type UnimplementedReleaseFlagSrvServer struct {
}

func (UnimplementedReleaseFlagSrvServer) CreateReleaseFlag(context.Context, *CreateReleaseFlagRequest) (*CreateReleaseFlagResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateReleaseFlag not implemented")
}
func (UnimplementedReleaseFlagSrvServer) mustEmbedUnimplementedReleaseFlagSrvServer() {}

// UnsafeReleaseFlagSrvServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ReleaseFlagSrvServer will
// result in compilation errors.
type UnsafeReleaseFlagSrvServer interface {
	mustEmbedUnimplementedReleaseFlagSrvServer()
}

func RegisterReleaseFlagSrvServer(s grpc.ServiceRegistrar, srv ReleaseFlagSrvServer) {
	s.RegisterService(&ReleaseFlagSrv_ServiceDesc, srv)
}

func _ReleaseFlagSrv_CreateReleaseFlag_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateReleaseFlagRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReleaseFlagSrvServer).CreateReleaseFlag(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pbs.ReleaseFlagSrv/CreateReleaseFlag",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReleaseFlagSrvServer).CreateReleaseFlag(ctx, req.(*CreateReleaseFlagRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ReleaseFlagSrv_ServiceDesc is the grpc.ServiceDesc for ReleaseFlagSrv service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ReleaseFlagSrv_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pbs.ReleaseFlagSrv",
	HandlerType: (*ReleaseFlagSrvServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateReleaseFlag",
			Handler:    _ReleaseFlagSrv_CreateReleaseFlag_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "protos/flagr.proto",
}
